apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    k8s-app: nginx
  namespace: apps
spec:
  selector:
    k8s-app: nginx
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    k8s-app: nginx-exporter
  namespace: apps
spec:
  selector:
    k8s-app: nginx
  ports:
    - name: nginx-exporter
      port: 9113 
      targetPort: 9113

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: apps
spec:
  rules:
  # This is your serving URL, it shout match with Django allow host in poll-configmap
  - host: your.serving.domain.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    k8s-app: nginx
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      containers:
        - image: trucv/nginx:latest
          imagePullPolicy: "Always"
          name: nginx
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - mountPath: /apps/polls/static
              name: staticfiles
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          args:
            - -nginx.scrape-uri=http://localhost/nginx/status
          ports:
            - containerPort: 9113
              name: nginx-exporter
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: nfs-pvc

